In progress
Emily774/emily774.github.io pull request #1
Opened 2021-01-19 09:09 UTC by Emily774

I have only done the html part of the webpage for now, will continue working on the CSS, but I could do with someone to look over what I've done so far. Great, thanks!

2021-01-19 09:54 UTC, damienscarpellini requested changes
Good stuff. A few minor things i've picked up on but nothing that seems to break the code.

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +<a target="_blank" href="https://www.history.com/topics/ancient-history/tutankhamen"> <img src="pexels-pixabay-33571.jpg" alt="Gold plated crest from the sarcophagi of Tutankharmun"></a>
<img> tag to go on a separate line. the closing </a> tag to go on the line after

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +<a target="_blank" href="https://www.history.com/topics/ancient-history/tutankhamen"> <img src="pexels-pixabay-33571.jpg" alt="Gold plated crest from the sarcophagi of Tutankharmun" width="100"></a>
<img> tag on next line down, closing </a> tag on line after

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +<h1>The second of Many Titles</h1>
second use of h1 should only be one h1 on page

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +	The Portuguese man o' war (Physalia physalis), also known as the man-of-war, bluebottle, or floating terror is a <a href="https://en.wikipedia.org/wiki/Hydrozoa">marine hydrozoan</a> found in the <a
enclose in a p tag

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +	<label for="">ImageTitle1</label>
no id

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +	<img src="pexels-csongor-kemény-3933541.jpg" alt="Image of an iron statue of a regal looking king with a halo behind his head situated amongst the trees in cloud" width="50" id="">
no id

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +<input type="email" name="email" id="email"/>
indent inline with the above tag

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +<input type="password" name="password" id="password"/>
indent inline with the above tag

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +<input type=“checkbox” name=“remember” id="remember"/>
indent inline with the above tag

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +<input type="submit" value="submit"/>
indent inline with the above tag

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +	<label for="">ImageTitle1</label>
i think you change this later on

2021-01-19 09:54 UTC, damienscarpellini commented on Portfolio1.html
> +	<img src="pexels-csongor-kemény-3933541.jpg" alt="Image of an iron statue of a regal looking king with a halo behind his head situated amongst the trees in cloud" width="50" id="">
i think you change this later on

2021-01-19 14:01 UTC, karenschulz commented on Portfolio1.html
> +	<a target="_blank" 	href="https://www.history.com/topics/ancient-history/tutankhamen"> <img src="pexels-pixabay-33571.jpg" alt="Gold plated 	crest from the sarcophagi of Tutankharmun, with a link to
line 16 alt="Gold plated 
don't have a closing "

2021-01-19 14:10 UTC, karenschulz commented on Portfolio1.html
> +	<a target="_blank" 	href="https://www.history.com/topics/ancient-history/tutankhamen"> <img src="pexels-pixabay-33571.jpg" alt="Gold plated 	crest from the sarcophagi of Tutankharmun, with a link to
Loved you had comments, easier to read

2021-01-20 15:44 UTC, Emily774 commented
This pr should have been put into the develop branch, so I've shifted it over. New pull request: https://github.com/Emily774/Portfolio-Webpage/pull/2#issue-558336889

2021-01-20 15:44 UTC, closed without merging